#!/bin/bash

set -exu

source="$1"
while [ 1 ]; do
	wla-gb -o test.o -D TEST_NAME=" ${source}" "${source}.s"
	wlalink -S linkfile "${source}.gb"
	sleep 1
	inotifywait -r -e close_write .
	sleep .1
done
